Purchased albums photos
wolox-training/mdt-express-js pull request #12
Opened 2019-07-16 00:33 UTC by manueltuero

## Summary
I added a new endpoint to allow get photos of purchased albums by album id

## Trello Card
https://trello.com/c/7mboJr8H

2019-07-18 18:47 UTC, jersonlopez requested changes

2019-07-18 18:47 UTC, jersonlopez commented on app/controllers/albums.js
> +    let query = {};
`let response = query = {};`

2019-07-18 18:47 UTC, jersonlopez commented on test/utils.js
> +    .get(`/users/albums/${id}/photos`)
this endpoint is our it should not be mocked

2019-07-18 18:47 UTC, jersonlopez commented on test/albums.test.js
> +    mockAlbumNotPurchasedError(1);
same here!

2019-07-18 19:42 UTC, manueltuero commented on app/controllers/albums.js
> +    let query = {};
This not works with eslint actual config :c

2019-07-19 13:24 UTC, jersonlopez requested changes

2019-07-19 13:24 UTC, jersonlopez commented on app/controllers/albums.js
> +      return res.status(200).send(photos);
return is unnecessary

2019-07-19 13:24 UTC, jersonlopez commented on app/controllers/albums.js
> +    return next(notFoundError(`The album id ${query.albumId} photos could not be obtained`));
same here!

2019-07-19 13:24 UTC, jersonlopez commented on app/controllers/albums.js
> +    return next(err);
and here!

2019-07-19 14:22 UTC, jersonlopez approved these changes

2019-07-19 14:28 UTC, merged